spring:
  application:
    name: ReviewService
  datasource:
    url: jdbc:mysql://localhost:3306/odoo
    username: root
    password: Realme6G90T
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8087