spring:
  application:
    name: AuthenticationService
  datasource:
    url: jdbc:mysql://localhost:3306/odoo
    username: root
    password: Realme6G90T
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

server:
  port: 8081